/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Additions only; removal/renaming is breaking. `#[non_exhaustive]` because new codes may appear within v1 itself (see `schema/README.md`) -- an exhaustive `match` outside this crate must add a wildcard arm, which is exactly the forward-compat behavior consumers need (an unrecognized code is not an error). `Other` covers the equivalent case for *deserialization* (this build reading JSON produced by a newer version).
 *
 * This interface was referenced by `ParseResult`'s JSON-Schema
 * via the `definition` "DiagCode".
 */
export type DiagCode =
  | (
      | "encoding_undetectable"
      | "encoding_mismatch"
      | "unclosed_tag"
      | "duplicate_statement_id"
      | "missing_statement_id"
      | "branch_limit_exceeded"
      | "unknown_element"
    )
  | "dangling_refid"
  | "oversize_input"
  | "duplicate_attribute"
  | "invalid_entity"
  | "unterminated_placeholder"
  | "nesting_limit_exceeded"
  | "include_at_wrapper_boundary"
  | "other";
/**
 * Closed set: an exhaustive `match` is a consumer feature (there's no forward-compat concern the way there is for `DiagCode`/`SqlText`, since `Unknown` already covers "neither of the two known dialects"). Adding a third dialect would be a v2.
 *
 * This interface was referenced by `ParseResult`'s JSON-Schema
 * via the `definition` "Dialect".
 */
export type Dialect = "mybatis" | "ibatis" | "unknown";
/**
 * Closed set: an exhaustive `match` is a consumer feature. `Dynamic` already covers "can't be resolved statically" -- there's no third kind of refid target. Adding a variant here would be a v2.
 *
 * ## Expansion-order contract
 *
 * This crate never substitutes the referenced `<sql>` fragment's text in place of the `<include>` token -- resolving `IncludeTarget` to actual SQL and splicing it in is entirely the consumer's job. MyBatis/iBatis themselves expand `<include>` *before* evaluating `<where>`/`<set>`/ `<trim>` dynamic semantics, so a wrapper's leading-AND/OR strip or trailing-comma strip sees the fragment's real, substituted text. Flattening here with the token still in place means a consumer substituting fragment text in afterward must, at minimum:
 *
 * - re-apply the wrapper's leading-AND/OR / trailing-comma cleanup to the substituted text when the include token was first/last inside a `<where>`/`<set>`/`<trim>`, and - treat a wrapper whose only content is an include token as conditional (the fragment may expand to nothing).
 *
 * `DiagCode::IncludeAtWrapperBoundary` flags exactly the spots this applies to -- see the README's "Include expansion order" section for the full write-up.
 *
 * This interface was referenced by `ParseResult`'s JSON-Schema
 * via the `definition` "IncludeTarget".
 */
export type IncludeTarget =
  | {
      local: string;
    }
  | {
      qualified: {
        id: string;
        ns: string;
        [k: string]: unknown;
      };
    }
  | "dynamic";
/**
 * Result of dynamic-tag flattening (MM-06). Branch combination cap N=32 — total candidates per statement, computed as the cartesian product of tag branches.
 *
 * `#[non_exhaustive]`: a third fallback representation is plausible future work, and consumers matching exhaustively today must not break at compile time if one's added.
 *
 * This interface was referenced by `ParseResult`'s JSON-Schema
 * via the `definition` "SqlText".
 */
export type SqlText =
  | {
      variants: SqlVariant[];
    }
  | {
      union: {
        /**
         * A **lower bound**, not necessarily the exact branch count: flattening bails out of cartesian expansion as soon as it's certain the total exceeds the cap, without finishing the (possibly much larger) exact count. Treat this as "at least this many, over the cap" rather than a precise total.
         */
        branch_count: number;
        text: SqlString;
        [k: string]: unknown;
      };
    };
/**
 * Closed set: an exhaustive `match` is a consumer feature. `Generic` already covers "some other statement-like tag with no CRUD-verb equivalent" -- a new MyBatis/iBatis statement-like tag would be recognized by adding to `Generic`'s callers, not by growing this enum. Adding a variant here would be a v2.
 *
 * This interface was referenced by `ParseResult`'s JSON-Schema
 * via the `definition` "StatementKind".
 */
export type StatementKind = ("select" | "insert" | "update" | "delete" | "procedure") | "generic";

export interface ParseResult {
  /**
   * Parsing never fails — every anomaly accumulates here.
   */
  diagnostics: Diagnostic[];
  dialect: Dialect;
  /**
   * The WHATWG name of the encoding the detection chain actually decoded the input with (`"UTF-8"`, `"EUC-KR"`, `"Shift_JIS"`, `"UTF-16LE"`, ...; `encoding_rs::Encoding::name()`'s own values, which are WHATWG-standard labels). `None` only when no decode was attempted at all (the raw-byte oversize cap rejected the input before `encoding.rs` ever ran) -- `parse` (already-decoded `&str` input) always reports `"UTF-8"`, since that's the one encoding a Rust `&str` can ever be.
   *
   * This is what makes the [`ByteSpan`] re-encoding caveat actionable: every span in this result is a byte offset into the UTF-8 text *after* decoding, so a consumer working with the **original** input bytes must decode them the same way first -- `new TextDecoder(result.encoding)` (Node.js/browsers both accept WHATWG labels directly), re-encode that decoded text to UTF-8, and slice spans against *that* buffer, not the original input bytes directly (see `wasm/README.md` for a worked recipe).
   *
   * BOM handling: for a document that opened with a byte-order mark, the mark is consumed during decoding and never appears in the decoded text -- spans are relative to the BOM-stripped content, same as every other span in this crate (offsets into what this crate's own decoding produced, not the original file's raw byte layout). A consumer re-decoding the original file with `TextDecoder` gets BOM-stripping for free (that's standard `TextDecoder` behavior for UTF-8/UTF-16 with a matching BOM), so no extra adjustment is needed on the consumer's side either.
   */
  encoding?: string | null;
  /**
   * `None` when the root element is not a mapper/sqlMap (reason is reported as a diagnostic).
   */
  mapper?: Mapper | null;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ParseResult`'s JSON-Schema
 * via the `definition` "Diagnostic".
 */
export interface Diagnostic {
  code: DiagCode;
  message: string;
  span?: ByteSpan | null;
  [k: string]: unknown;
}
/**
 * Half-open range `[start, end)`: byte offsets into the UTF-8 text as decoded by this crate (identical to raw input bytes for UTF-8 sources; see the caveat below for re-encoded documents).
 *
 * Caveat: this holds exactly for UTF-8 input, which decoding leaves byte-for-byte unchanged. For documents decoded from any other encoding (EUC-KR, Shift_JIS, GB18030, UTF-16, ... -- see `encoding.rs`, which supports every WHATWG encoding via a BOM/declared-label-driven chain, not just EUC-KR), decoding to UTF-8 changes byte *widths* per character, so spans on such documents are offsets into the re-encoded UTF-8 string, not the original raw bytes. This applies uniformly to every re-encoded document, not just Korean legacy files. Consumers reading spans back against a source file must decode that source the same way this crate did before slicing.
 *
 * This interface was referenced by `ParseResult`'s JSON-Schema
 * via the `definition` "ByteSpan".
 */
export interface ByteSpan {
  end: number;
  start: number;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ParseResult`'s JSON-Schema
 * via the `definition` "Mapper".
 */
export interface Mapper {
  fragments: SqlFragment[];
  /**
   * Usually `None` for iBatis sqlMaps (observed in the wild: the prefix lives inside the statement id itself, e.g. `WidgetDAO.getWidget`).
   */
  namespace?: SpannedFor_String | null;
  result_maps: ResultMap[];
  statements: Statement[];
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ParseResult`'s JSON-Schema
 * via the `definition` "SqlFragment".
 */
export interface SqlFragment {
  id: SpannedFor_String;
  /**
   * Nested includes inside the fragment (MM-04).
   */
  includes: SpannedFor_IncludeRef[];
  /**
   * Full original extent: opening-tag start → subtree end.
   */
  span: ByteSpan;
  sql: SqlText;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ParseResult`'s JSON-Schema
 * via the `definition` "Spanned_for_String".
 */
export interface SpannedFor_String {
  span: ByteSpan;
  value: string;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ParseResult`'s JSON-Schema
 * via the `definition` "Spanned_for_IncludeRef".
 */
export interface SpannedFor_IncludeRef {
  span: ByteSpan;
  value: IncludeRef;
  [k: string]: unknown;
}
/**
 * The include-token textual contract -- a stable part of the v1 output.
 *
 * Every `<include refid="...">` marker renders into the flattened [`SqlText`] as a SQL block comment: an opening `/`+`*`, the literal text `batis:include(`, this struct's own `raw` field, a closing `)`, then the closing `*`+`/`. `raw` is rendered verbatim -- the unparsed `refid` attribute value -- **except** any literal `*` immediately followed by `/` inside it is rewritten to `*` + `_` + `/`, so the token can never terminate its own enclosing comment early (a `refid` is untrusted XML attribute content, not something this crate controls the shape of). This holds regardless of `target`'s classification: `Local("frag")` renders the comment around `frag` verbatim; `Qualified { ns: "otherNs", id: "frag" }` renders the *original, still-dotted* text `otherNs.frag` (`raw` is the whole unparsed attribute value; `ns`/`id` are just it split on the last dot for convenience, not a separate rendering); `Dynamic` renders the literal, unresolved `${...}` text as-is.
 *
 * **Locating tokens**: since the token's opening (`/`+`*` followed by the literal text `batis:include(`) is a fixed prefix, a plain substring search over the flattened SQL text finds every token directly -- no need to reconstruct it from `raw` first. Each token's position correlates 1:1 with one entry in the owning [`Statement::includes`]/[`SqlFragment::includes`] list: match by `Spanned::span`, which is the *original XML* span of the `<include>` element (not a position in the flattened text) -- the same span a [`DiagCode::IncludeAtWrapperBoundary`] diagnostic reports when this token sits at a `<where>`/`<set>`/`<trim>` boundary (see that variant's own doc comment, and the README's "Include expansion order" section, for the substitution contract itself).
 *
 * **Substituting a fragment with multiple variants**: a referenced `<sql>` fragment is itself flattened to a [`SqlText`], which may be `Variants` (several condition-gated alternatives) rather than one fixed string. There is no single deterministic substitution in that case -- the fragment's *own* active variant depends on the same runtime parameter state as the enclosing statement's variant does, so a consumer substituting fragment text into one variant of the parent statement must pick the matching variant of the fragment (by `conditions`), not an arbitrary one (e.g. `variants[0]`).
 *
 * **Document order**: [`Mapper::statements`] (and `fragments`/ `result_maps`) preserve source document order -- safe to assume when resolving forward/backward references across statements in one file.
 *
 * **Diagnostic messages are not a stable matching surface.** `message` strings may be reworded between versions without that being a breaking change; match on [`Diagnostic::code`] instead.
 *
 * This interface was referenced by `ParseResult`'s JSON-Schema
 * via the `definition` "IncludeRef".
 */
export interface IncludeRef {
  raw: string;
  target: IncludeTarget;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ParseResult`'s JSON-Schema
 * via the `definition` "SqlVariant".
 */
export interface SqlVariant {
  /**
   * The `test` expressions (verbatim) that activate this variant -- positive-only, and not a full boolean formula.
   *
   * Only the `test` conditions of `<if>`/dynamic tags whose branch is actually *taken* in this variant's path through the tag tree are recorded here, in document order. An `<if>`'s *not-taken* path contributes an alternative with `conditions: []` (empty) -- which is indistinguishable, at the type level, from a statement that had no `<if>` at all. This is by design (recording "this condition was false" would require inventing a negated-expression representation this crate doesn't have a use for elsewhere), but it means an empty `conditions` list is not itself proof that a variant is unconditional -- a consumer that needs that distinction has to correlate against the source XML's own dynamic-tag structure.
   *
   * `SqlText::Variants` as a whole lists *candidate* SQL shapes, not a runtime guarantee: this crate has no visibility into actual parameter values, so it cannot say which variant (if any single one) will execute for a given call -- only that these are the shapes the dynamic-tag tree can produce, gated by the conditions listed here.
   */
  conditions: string[];
  text: SqlString;
  [k: string]: unknown;
}
/**
 * Flattened SQL text plus a mapping back to the source.
 *
 * This interface was referenced by `ParseResult`'s JSON-Schema
 * via the `definition` "SqlString".
 */
export interface SqlString {
  /**
   * (synthetic-text offset, original byte offset) segment-start pairs — strictly increasing.
   */
  span_map: [number, number][];
  /**
   * Placeholders already normalized: `#{..}` → `?`, `${..}` → `__BATIS_DYN__`.
   */
  text: string;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ParseResult`'s JSON-Schema
 * via the `definition` "ResultMap".
 */
export interface ResultMap {
  extends?: SpannedFor_String | null;
  id: SpannedFor_String;
  mappings: ColumnMapping[];
  /**
   * Full original extent: opening-tag start → subtree end.
   */
  span: ByteSpan;
  type_ref?: SpannedFor_ClassRef | null;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ParseResult`'s JSON-Schema
 * via the `definition` "ColumnMapping".
 */
export interface ColumnMapping {
  column?: string | null;
  property?: string | null;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ParseResult`'s JSON-Schema
 * via the `definition` "Spanned_for_ClassRef".
 */
export interface SpannedFor_ClassRef {
  span: ByteSpan;
  value: ClassRef;
  [k: string]: unknown;
}
/**
 * Alias resolution is the consumer's job — only the raw text is kept.
 *
 * This interface was referenced by `ParseResult`'s JSON-Schema
 * via the `definition` "ClassRef".
 */
export interface ClassRef {
  raw: string;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ParseResult`'s JSON-Schema
 * via the `definition` "Statement".
 */
export interface Statement {
  /**
   * MyBatis per-vendor branching (`databaseId="oracle"` etc.) — `None` when the statement doesn't declare one. Distinguishes otherwise duplicate ids (MM-03).
   */
  database_id?: SpannedFor_String | null;
  /**
   * `None` when missing, plus a `MissingStatementId` diagnostic. Synthesized ids are never invented.
   */
  id?: SpannedFor_String | null;
  includes: SpannedFor_IncludeRef[];
  kind: StatementKind;
  param_class?: SpannedFor_ClassRef | null;
  /**
   * Expression paths collected from `#{a.b}` / `${c}` (MM-07).
   */
  property_paths: SpannedFor_String[];
  result_class?: SpannedFor_ClassRef | null;
  result_map_ref?: SpannedFor_String | null;
  /**
   * Full original extent of the statement: opening-tag start → subtree end (i.e. past its closing tag, or its own end for a self-closed element).
   */
  span: ByteSpan;
  sql: SqlText;
  [k: string]: unknown;
}
