/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Additions only; removal/renaming is breaking.
 *
 * This interface was referenced by `ParseResult`'s JSON-Schema
 * via the `definition` "DiagCode".
 */
export type DiagCode =
  | (
      | "encoding_undetectable"
      | "encoding_mismatch"
      | "unclosed_tag"
      | "duplicate_statement_id"
      | "missing_statement_id"
      | "dangling_refid"
      | "branch_limit_exceeded"
      | "unknown_element"
      | "oversize_input"
    )
  | "duplicate_attribute"
  | "invalid_entity"
  | "unterminated_placeholder"
  | "nesting_limit_exceeded";
/**
 * This interface was referenced by `ParseResult`'s JSON-Schema
 * via the `definition` "Dialect".
 */
export type Dialect = "mybatis" | "ibatis" | "unknown";
/**
 * This interface was referenced by `ParseResult`'s JSON-Schema
 * via the `definition` "IncludeTarget".
 */
export type IncludeTarget =
  | {
      local: string;
    }
  | {
      qualified: {
        id: string;
        ns: string;
        [k: string]: unknown;
      };
    }
  | "dynamic";
/**
 * Result of dynamic-tag flattening (MM-06). Branch combination cap N=32 — total candidates per statement, computed as the cartesian product of tag branches.
 *
 * This interface was referenced by `ParseResult`'s JSON-Schema
 * via the `definition` "SqlText".
 */
export type SqlText =
  | {
      variants: SqlVariant[];
    }
  | {
      union: {
        branch_count: number;
        text: SqlString;
        [k: string]: unknown;
      };
    };
/**
 * This interface was referenced by `ParseResult`'s JSON-Schema
 * via the `definition` "StatementKind".
 */
export type StatementKind = ("select" | "insert" | "update" | "delete" | "procedure") | "generic";

export interface ParseResult {
  /**
   * Parsing never fails — every anomaly accumulates here.
   */
  diagnostics: Diagnostic[];
  dialect: Dialect;
  /**
   * `None` when the root element is not a mapper/sqlMap (reason is reported as a diagnostic).
   */
  mapper?: Mapper | null;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ParseResult`'s JSON-Schema
 * via the `definition` "Diagnostic".
 */
export interface Diagnostic {
  code: DiagCode;
  message: string;
  span?: ByteSpan | null;
  [k: string]: unknown;
}
/**
 * Half-open range `[start, end)` in **original bytes** — never in the decoded string.
 *
 * Caveat: this holds exactly for UTF-8 input, which decoding leaves byte-for-byte unchanged. For documents that were re-encoded from EUC-KR/CP949 (see `encoding.rs`), decoding to UTF-8 changes byte *widths* per character, so spans on such documents are offsets into the re-encoded UTF-8 string, not the original raw bytes. Consumers reading spans back against a source file must decode that source the same way this crate did before slicing.
 *
 * This interface was referenced by `ParseResult`'s JSON-Schema
 * via the `definition` "ByteSpan".
 */
export interface ByteSpan {
  end: number;
  start: number;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ParseResult`'s JSON-Schema
 * via the `definition` "Mapper".
 */
export interface Mapper {
  fragments: SqlFragment[];
  /**
   * Usually `None` for iBatis sqlMaps (observed in the wild: the prefix lives inside the statement id itself, e.g. `WidgetDAO.getWidget`).
   */
  namespace?: SpannedFor_String | null;
  result_maps: ResultMap[];
  statements: Statement[];
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ParseResult`'s JSON-Schema
 * via the `definition` "SqlFragment".
 */
export interface SqlFragment {
  id: SpannedFor_String;
  /**
   * Nested includes inside the fragment (MM-04).
   */
  includes: SpannedFor_IncludeRef[];
  /**
   * Full original extent: opening-tag start → subtree end.
   */
  span?: ByteSpan;
  sql: SqlText;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ParseResult`'s JSON-Schema
 * via the `definition` "Spanned_for_String".
 */
export interface SpannedFor_String {
  span: ByteSpan;
  value: string;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ParseResult`'s JSON-Schema
 * via the `definition` "Spanned_for_IncludeRef".
 */
export interface SpannedFor_IncludeRef {
  span: ByteSpan;
  value: IncludeRef;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ParseResult`'s JSON-Schema
 * via the `definition` "IncludeRef".
 */
export interface IncludeRef {
  raw: string;
  target: IncludeTarget;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ParseResult`'s JSON-Schema
 * via the `definition` "SqlVariant".
 */
export interface SqlVariant {
  /**
   * The `test` expressions (verbatim) that activate this variant.
   */
  conditions: string[];
  text: SqlString;
  [k: string]: unknown;
}
/**
 * Flattened SQL text plus a mapping back to the source.
 *
 * This interface was referenced by `ParseResult`'s JSON-Schema
 * via the `definition` "SqlString".
 */
export interface SqlString {
  /**
   * (synthetic-text offset, original byte offset) segment-start pairs — strictly increasing.
   */
  span_map: [number, number][];
  /**
   * Placeholders already normalized: `#{..}` → `?`, `${..}` → `__BATIS_DYN__`.
   */
  text: string;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ParseResult`'s JSON-Schema
 * via the `definition` "ResultMap".
 */
export interface ResultMap {
  extends?: SpannedFor_String | null;
  id: SpannedFor_String;
  mappings: ColumnMapping[];
  /**
   * Full original extent: opening-tag start → subtree end.
   */
  span?: ByteSpan;
  type_ref?: SpannedFor_ClassRef | null;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ParseResult`'s JSON-Schema
 * via the `definition` "ColumnMapping".
 */
export interface ColumnMapping {
  column?: string | null;
  property?: string | null;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ParseResult`'s JSON-Schema
 * via the `definition` "Spanned_for_ClassRef".
 */
export interface SpannedFor_ClassRef {
  span: ByteSpan;
  value: ClassRef;
  [k: string]: unknown;
}
/**
 * Alias resolution is the consumer's job — only the raw text is kept.
 *
 * This interface was referenced by `ParseResult`'s JSON-Schema
 * via the `definition` "ClassRef".
 */
export interface ClassRef {
  raw: string;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ParseResult`'s JSON-Schema
 * via the `definition` "Statement".
 */
export interface Statement {
  /**
   * MyBatis per-vendor branching (`databaseId="oracle"` etc.) — `None` when the statement doesn't declare one. Distinguishes otherwise duplicate ids (MM-03).
   */
  database_id?: SpannedFor_String | null;
  /**
   * `None` when missing, plus a `MissingStatementId` diagnostic. Synthesized ids are never invented.
   */
  id?: SpannedFor_String | null;
  includes: SpannedFor_IncludeRef[];
  kind: StatementKind;
  param_class?: SpannedFor_ClassRef | null;
  /**
   * Expression paths collected from `#{a.b}` / `${c}` (MM-07).
   */
  property_paths: SpannedFor_String[];
  result_class?: SpannedFor_ClassRef | null;
  result_map_ref?: SpannedFor_String | null;
  /**
   * Full original extent of the statement: opening-tag start → subtree end (i.e. past its closing tag, or its own end for a self-closed element).
   */
  span?: ByteSpan;
  sql: SqlText;
  [k: string]: unknown;
}
