//! Parsing core — quick-xml event stream feeding a custom tree builder.
//!
//! Owned micro-features: MM-01 (root/dialect detection), MM-02 (namespace),
//! MM-03 (statement collection), MM-04 (`<sql>` fragments), MM-05 (include),
//! MM-08 (CDATA/entities), MM-09 (class refs), MM-10 (resultMap),
//! MM-11 (iBatis dialect), MM-12 (span preservation), MM-13 (hostile-input
//! resilience).
//!
//! Recovery rules (fixed by spec):
//! 1. Unclosed tag → implicitly closed when the parent closes, plus
//!    `UnclosedTag`.
//! 2. Orphan closing tag → ignored, plus a diagnostic.
//! 3. Duplicate attribute → first value wins, plus a diagnostic.
//! 4. Non-XML residue → skip to the next `<` and resynchronize.
//!
//! Constants: 10 MB input cap (`OversizeInput`); the branch cap lives in
//! [`crate::flatten`].

use crate::model::*;
use quick_xml::events::Event;
use quick_xml::reader::Reader;

/// MM-01: identifies the root element and derives the dialect from its
/// name (`<mapper>` → MyBatis, `<sqlMap>` → iBatis). Any other root leaves
/// `mapper: None` (diagnostics land in a later slice).
pub(crate) fn parse_str(source: &str) -> ParseResult {
    let mut reader = Reader::from_str(source);

    loop {
        let start = reader.buffer_position();
        match reader.read_event() {
            Ok(Event::Start(tag)) | Ok(Event::Empty(tag)) => {
                let end = reader.buffer_position();
                let name = tag.local_name();
                let name = name.as_ref();
                return match name {
                    b"mapper" => ParseResult {
                        dialect: Dialect::Mybatis,
                        mapper: Some(empty_mapper()),
                        diagnostics: Vec::new(),
                    },
                    b"sqlMap" => ParseResult {
                        dialect: Dialect::Ibatis,
                        mapper: Some(empty_mapper()),
                        diagnostics: Vec::new(),
                    },
                    other => ParseResult {
                        dialect: Dialect::Unknown,
                        mapper: None,
                        diagnostics: vec![Diagnostic {
                            code: DiagCode::UnknownElement,
                            span: Some(ByteSpan {
                                start: start as u32,
                                end: end as u32,
                            }),
                            message: format!(
                                "root element <{}> is not a mapper/sqlMap",
                                String::from_utf8_lossy(other)
                            ),
                        }],
                    },
                };
            }
            Ok(Event::Eof) => {
                return ParseResult {
                    dialect: Dialect::Unknown,
                    mapper: None,
                    diagnostics: vec![Diagnostic {
                        code: DiagCode::UnknownElement,
                        span: None,
                        message: "no root element found".to_string(),
                    }],
                };
            }
            Err(err) => {
                let pos = reader.error_position();
                return ParseResult {
                    dialect: Dialect::Unknown,
                    mapper: None,
                    diagnostics: vec![Diagnostic {
                        code: DiagCode::UnclosedTag,
                        span: Some(ByteSpan {
                            start: pos as u32,
                            end: pos as u32,
                        }),
                        message: format!("XML parse error: {err}"),
                    }],
                };
            }
            _ => continue,
        }
    }
}

fn empty_mapper() -> Mapper {
    Mapper {
        namespace: None,
        statements: Vec::new(),
        fragments: Vec::new(),
        result_maps: Vec::new(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn mm_01_mapper_root_is_mybatis_dialect() {
        let source = r#"<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN"
  "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="com.example.demo.mapper.WidgetMapper">
</mapper>"#;
        let result = parse_str(source);
        assert_eq!(result.dialect, Dialect::Mybatis);
        assert!(result.mapper.is_some());
    }

    #[test]
    fn mm_01_sqlmap_root_is_ibatis_dialect() {
        let source = r#"<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sqlMap PUBLIC "-//ibatis.apache.org//DTD SQL Map 2.0//EN"
  "http://ibatis.apache.org/dtd/sql-map-2.dtd">
<sqlMap>
</sqlMap>"#;
        let result = parse_str(source);
        assert_eq!(result.dialect, Dialect::Ibatis);
        assert!(result.mapper.is_some());
    }

    #[test]
    fn mm_01_leading_comment_before_root_is_skipped() {
        let source =
            "<!-- generated by legacy codegen, do not edit -->\n<mapper namespace=\"x\"></mapper>";
        let result = parse_str(source);
        assert_eq!(result.dialect, Dialect::Mybatis);
        assert!(result.mapper.is_some());
    }

    #[test]
    fn mm_01_bom_before_root_is_skipped() {
        let source = "\u{FEFF}<mapper namespace=\"x\"></mapper>";
        let result = parse_str(source);
        assert_eq!(result.dialect, Dialect::Mybatis);
        assert!(result.mapper.is_some());
    }

    #[test]
    fn mm_01_configuration_root_yields_no_mapper() {
        let source = r#"<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuration PUBLIC "-//mybatis.org//DTD Config 3.0//EN"
  "http://mybatis.org/dtd/mybatis-3-config.dtd">
<configuration>
</configuration>"#;
        let result = parse_str(source);
        assert_eq!(result.dialect, Dialect::Unknown);
        assert!(result.mapper.is_none());
        assert_eq!(result.diagnostics.len(), 1);
        assert_eq!(result.diagnostics[0].code, DiagCode::UnknownElement);
        assert!(result.diagnostics[0].span.is_some());
    }

    #[test]
    fn mm_01_malformed_input_yields_diagnostic_not_silence() {
        let source = "<mapper namespace=\"x\"";
        let result = parse_str(source);
        assert_eq!(result.dialect, Dialect::Unknown);
        assert!(result.mapper.is_none());
        assert_eq!(result.diagnostics.len(), 1);
    }
}
